"""add payment_method and transaction_time

Revision ID: 71bd8bfb8669
Revises: 
Create Date: 2026-02-25 13:26:23.449525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bd8bfb8669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orders', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'transaction_time')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'razorpay_order_id')
    # ### end Alembic commands ###
